name: 'Delete branch on merge'
on:
  pull_request:
    types:
      - closed
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve the branch name related to the current pull request and its URL
        id: current_pr_branch
        uses: stefanbauer/action-current-pr-branch@v1
        with:
          github_token: ${{ secrets.TOKEN }}
      - name: Delete merged branch
        uses: koj-co/delete-merged-action@master
        with:
          branches: "!master,!main, ${{ steps.current_pr_branch.outputs.branch_name }}"
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN }}"